Repository KonferCA/SpurHacks-Dashboard, pull requests merged in 2025-06, with the labels that each got.

#110 Add finished design of perks page (perks are not updated yet since we don't have the final list)
  src/components/PageWrapper/PageWrapper.tsx
  src/components/Perk.tsx
  src/data/perks.ts
  src/pages/perks.page.tsx
  src/providers/RoutesProvider/data.ts
Labels: enhancement, frontend

#125 Hide schedule, team, ticket, and perks pages & add revoke rsvp
  functions/package.json
  functions/src/index.ts
  functions/src/rsvp.ts
  functions/src/utils.ts
  src/components/Perk.tsx
  src/pages/home.page.tsx
  src/pages/miscellaneous/verify-rsvp.page.tsx
  src/pages/perks.page.tsx
  src/providers/RoutesProvider/RoutesProvider.tsx
  src/providers/RoutesProvider/accessChecks.ts
  src/services/firebase/rsvp.ts
Labels: backend, enhancement, frontend

#130 Update Google Wallet Ticket Design & Small refactor
  functions/src/google.ts
  functions/src/index.ts
  public/google-wallet-header-pic.png
  public/gradient-icon.png
  src/pages/my-ticket.page.tsx
Labels: backend, enhancement, frontend

#132 Fix qr code stuck in loading & refactor home cooked qr code generation
  functions/src/index.ts
  functions/src/ticket.ts
  functions/src/types.ts
  src/components/Navbar.tsx
  src/pages/my-ticket.page.tsx
  src/services/firebase/ticket.ts
  src/vite-env.d.ts
Labels: backend, bug, enhancement, frontend

#135 Add faq card to home page
  src/data/faqs.ts
  src/pages/home.page.tsx
Labels: enhancement, frontend

#134 Feat/99/account page
  config/firestore.rules
  functions/src/index.ts
  src/components/Navbar.tsx
  src/components/PhoneInput/PhoneInput.tsx
  src/pages/account.page.tsx
  src/providers/RoutesProvider/RoutesProvider.tsx
  src/providers/RoutesProvider/data.ts
  src/services/firebase/application.ts
  src/services/firebase/emergency-contact.ts
Labels: backend, enhancement, frontend

#145 Fix the entire team creation flow
  functions/src/index.ts
  functions/src/teams.ts
  src/components/InfoCallout/InfoCallout.tsx
  src/components/InfoCard/Card.test.tsx
  src/components/InfoCard/Card.tsx
  src/components/index.tsx
  src/pages/home.page.tsx
  src/pages/my-team.page.tsx
  src/services/firebase/teams.ts
  src/services/firebase/types.ts
Labels: backend, bug, enhancement, frontend, refactor

#146 Merge networking and profile pages
  config/storage.rules
  functions/src/index.ts
  package.json
  public/icons/pdf-icon.png
  src/components/Navbar.tsx
  src/components/ProfilePicture/ProfilePicture.tsx
  src/components/ProfilePicture/index.ts
  src/components/index.tsx
  src/forms/hacker-form/types.ts
  src/hooks/use-profile-picture.ts
  src/pages/networking.page.tsx
  src/services/firebase/application.ts
  src/services/firebase/files.ts
  src/services/firebase/types.ts
  src/stores/user.store.ts
Labels: backend, bug, enhancement, frontend, refactor

#154 [fix] clipped logo
  src/components/LoadingAnimation.tsx
Labels: bug, frontend
