Repository KonferCA/SpurHacks-Dashboard, pull requests merged in 2025-05, with the labels that each got.

#27 fix: lint and typecheck
  .github/workflows/code-quality.yml
  .gitignore
  biome.json
  src/components/FileBrowse/FileBrowse.tsx
  src/components/Modal.tsx
  src/components/Navbar.tsx
  src/components/Schedule/Schedule.tsx
  src/components/Steps/Steps.tsx
  src/components/forms/types.ts
  src/hooks/use-applications.ts
  src/main.tsx
  src/pages/admin/view-ticket.page.tsx
  src/pages/apply.page.tsx
  src/pages/login.page.tsx
  src/pages/miscellaneous/post-submission.page.tsx
  src/pages/my-team.page.tsx
  src/pages/my-ticket.page.tsx
  src/pages/networking.page.tsx
  src/pages/perks.page.tsx
  src/providers/RoutesProvider/types.ts
  tsconfig.node.tsbuildinfo
  vite.config.d.ts
  vite.config.ts
Labels: enhancement

#26 refactored TextInput
  src/components/TextInput/TextInput.styles.ts
  src/components/TextInput/TextInput.tsx
  src/pages/login.page.tsx
Labels: frontend, refactor

#29 Generalize hacker form validation
  src/components/Application.tsx
  src/components/MultiSelect/MultiSelect.tsx
  src/components/Select/Select.tsx
  src/components/forms/validations.ts
  src/data/ages.ts
  src/data/appCloseDate.ts
  src/data/cities.ts
  src/data/countryNames.ts
  src/data/countryPhoneCodes.ts
  src/data/index.ts
  src/forms/hacker-form/defaults.ts
  src/forms/hacker-form/types.ts
  src/forms/hacker-form/validations.ts
  src/hooks/use-applications.ts
  src/pages/apply.page.tsx
  src/providers/RoutesProvider/RoutesProvider.tsx
  src/services/firebase/application.ts
Labels: enhancement, frontend

#42 Update index.html metadata
  index.html
  public/icon.png
  public/icon.svg
Labels: URGENT, enhancement, frontend

#45 [fix] missing astrix on required components
  src/components/Select/Select.tsx
Labels: URGENT, bug, frontend

#51 Fix select component bugs
  src/components/Select/Select.tsx
Labels: enhancement, frontend

#54 Polish login page visuals and interactions
  src/assets/index.tsx
  src/assets/spur-logo-offwhite.svg
  src/components/LoadingAnimation.tsx
  src/components/ui/field.tsx
  src/components/ui/password-input.tsx
  src/pages/login.page.tsx
  src/pages/miscellaneous/verify-email.page.tsx
  src/providers/AuthProvider/AuthProvider.tsx
Labels: enhancement, frontend

#55 using svgs instead of react-icons
  src/assets/discord.svg
  src/assets/index.tsx
  src/assets/instagram.svg
  src/assets/linkedin.svg
  src/assets/tiktok.svg
  src/assets/x.svg
  src/components/Navbar.tsx
  src/pages/home.page.tsx
Labels: bug, frontend

#60 [update] discord validation and add description to travel item
  src/forms/hacker-form/validations.ts
  src/pages/apply.page.tsx
Labels: URGENT, bug, frontend

#63 Update Select, MultiSelect, TextInput, TextArea styles & fix PhoneInput allowing infinity number length
  src/components/MultiSelect.tsx
  src/components/PhoneInput/PhoneInput.tsx
  src/components/Select/Select.tsx
  src/components/TextArea/TextArea.tsx
  src/components/TextInput/TextInput.tsx
  src/hooks/use-applications.ts
  src/index.css
  src/pages/apply.page.tsx
Labels: bug, enhancement, frontend

#65 Refactor Select component
  src/components/Select/Select.tsx
Labels: bug, frontend

#56 Fix/0/fix login flash
  biome.json
  functions/src/index.ts
  package.json
  src/assets/index.tsx
  src/components/Application.tsx
  src/components/AuthLoadingGuard.tsx
  src/components/FileBrowse/FileBrowse.tsx
  src/components/PageWrapper/PageWrapper.tsx
  src/components/PhoneInput/PhoneInput.tsx
  src/components/RouterChakraLink.tsx
  src/components/Select/Select.tsx
  src/components/TextInput/TextInput.tsx
  src/forms/hacker-form/validations.ts
  src/hooks/use-applications.ts
  src/main.tsx
  src/pages/apply.page.tsx
  src/pages/home.page.tsx
  src/pages/login.page.tsx
  src/pages/miscellaneous/not-found.page.tsx
  src/pages/miscellaneous/verify-email.page.tsx
  src/providers/AuthProvider/AuthProvider.tsx
  src/providers/RoutesProvider/RoutesProvider.tsx
  src/services/firebase/application.ts
  src/services/firebase/files.ts
Labels: refactor

#67 Fix hint colour being wrong + corrected theme definition
  src/components/FileBrowse/FileBrowse.tsx
  src/components/Navbar.tsx
  src/components/Select/Select.tsx
  src/components/TextArea/TextArea.tsx
  src/components/TextInput/TextInput.tsx
  src/components/ui/theme.ts
  src/index.css
  src/pages/home.page.tsx
Labels: bug, enhancement, frontend

#70 Add MJV Typeform card to home page
  data/auth_export/accounts.json
  data/firestore_export/all_namespaces/all_kinds/all_namespaces_all_kinds.export_metadata
  data/firestore_export/all_namespaces/all_kinds/output-0
  data/firestore_export/firestore_export.overall_export_metadata
  data/storage_export/blobs/67a1b2c8-4f98-4bbf-aa4d-033b88510ecf
  data/storage_export/blobs/b0dd4728-2896-4287-842a-c76715327651
  data/storage_export/metadata/67a1b2c8-4f98-4bbf-aa4d-033b88510ecf.json
  data/storage_export/metadata/b0dd4728-2896-4287-842a-c76715327651.json
  src/pages/home.page.tsx
  src/services/firebase/misc.ts
Labels: enhancement, frontend

#72 Update discord validation to allow prefixing @
  src/forms/hacker-form/validations.ts
Labels: bug, frontend

#74 fix hasApplied access check wrongly returning a true value
  src/providers/RoutesProvider/accessChecks.ts
Labels: bug, frontend

#77 Change all HH to SH
  README.md
  docs/CONTRIBUTING.md
  functions/src/apple.ts
  functions/src/google.ts
  functions/src/rsvp.ts
  functions/src/teams.ts
  src/components/Application.tsx
  src/components/PageWrapper/PageWrapper.tsx
  src/components/SocialIcons/SocialIcons.tsx
  src/forms/hacker-form/validations.ts
  src/pages/application.page.tsx
  src/pages/login.page.test.tsx
  src/pages/miscellaneous/post-submission.page.tsx
  src/pages/miscellaneous/verify-rsvp.page.tsx
  src/pages/my-ticket.page.tsx
  src/providers/RoutesProvider/data.ts
Labels: bug, frontend

#84 Update access checks for certain pages
  src/providers/RoutesProvider/RoutesProvider.tsx
Labels: bug, enhancement, frontend

#83 Add missing hacker statuses
  src/components/ui/theme.ts
  src/hooks/use-applications.ts
  src/pages/home.page.tsx
Labels: bug, frontend

#87 Update style for my-ticket page
  src/pages/my-ticket.page.tsx
  src/providers/RoutesProvider/data.ts
Labels: enhancement, frontend

#109 add travel and talent cards in home page
  src/pages/home.page.tsx
  src/services/firebase/misc.ts
Labels: enhancement, frontend
